name = "GadPack"
author = "G&D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c050cbfd24d59ba0a1ffa903868cf1759c229a4062073338ec3b17873d6b3d"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
