name = "GadPack"
author = "G&D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "505b17dbb0b4774fe6d31873e48365b843cdb085ac77b63729852ca608767afd"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
